apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginx
  labels:
    app: my-pv

spec:
  capacity:
    storage: 1Gi

  accessModes: 
    - ReadWriteOnce

  persistentVolumeRetainPolicy: Retain 
  storageClassName: local-storage
  hostPath:
    - /mnt/data