apiVersion: v1
kind: Service
metadata: 
  name: notes-app-Service
  namespace: nginx
spec: 
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort